# Q1) Write a Python code to implement the KNN classifier algorithm on load_iris dataset in sklearn.datasets.

In [38]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [39]:
data=load_iris()

In [40]:
X=pd.DataFrame(data=data.data,columns=data.feature_names)
y=data.target

In [41]:
X.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [42]:
# Train test split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=1/3,random_state=10)

In [43]:
knn=KNeighborsClassifier()

In [44]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [45]:
y_pred=knn.predict(X_test)

In [47]:
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.96
[[15  0  0]
 [ 0 17  2]
 [ 0  0 16]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      0.89      0.94        19
           2       0.89      1.00      0.94        16

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



# Q2) Write a Python code to implement the KNN regressor algorithm on load_boston dataset in sklearn.datasets

In [48]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor

ImportError: 
`load_boston` has been removed from scikit-learn since version 1.2.

The Boston housing prices dataset has an ethical problem: as
investigated in [1], the authors of this dataset engineered a
non-invertible variable "B" assuming that racial self-segregation had a
positive impact on house prices [2]. Furthermore the goal of the
research that led to the creation of this dataset was to study the
impact of air quality but it did not give adequate demonstration of the
validity of this assumption.

The scikit-learn maintainers therefore strongly discourage the use of
this dataset unless the purpose of the code is to study and educate
about ethical issues in data science and machine learning.

In this special case, you can fetch the dataset from the original
source::

    import pandas as pd
    import numpy as np

    data_url = "http://lib.stat.cmu.edu/datasets/boston"
    raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
    data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
    target = raw_df.values[1::2, 2]

Alternative datasets include the California housing dataset and the
Ames housing dataset. You can load the datasets as follows::

    from sklearn.datasets import fetch_california_housing
    housing = fetch_california_housing()

for the California housing dataset and::

    from sklearn.datasets import fetch_openml
    housing = fetch_openml(name="house_prices", as_frame=True)

for the Ames housing dataset.

[1] M Carlisle.
"Racist data destruction?"
<https://medium.com/@docintangible/racist-data-destruction-113e3eff54a8>

[2] Harrison Jr, David, and Daniel L. Rubinfeld.
"Hedonic housing prices and the demand for clean air."
Journal of environmental economics and management 5.1 (1978): 81-102.
<https://www.researchgate.net/publication/4974606_Hedonic_housing_prices_and_the_demand_for_clean_air>


In [49]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.datasets import fetch_california_housing

# I am using california housing because we can see in the above code load_boston is not currently available

In [25]:
housing=fetch_california_housing()

In [50]:
X1=pd.DataFrame(data=housing.data,columns=housing.feature_names)
y1=housing.target

In [51]:
X1.isnull().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
dtype: int64

In [54]:
# Train test split
X_train1,X_test1,y_train1,y_test1=train_test_split(X1,y1,test_size=1/3,random_state=10)

In [55]:
knnr=KNeighborsRegressor()

In [56]:
knnr.fit(X_train1,y_train1)

KNeighborsRegressor()

In [57]:
y_pred_regressor=knnr.predict(X_test1)

In [58]:
from sklearn.metrics import r2_score,mean_absolute_error
print(r2_score(y_test1,y_pred_regressor))
print(mean_absolute_error(y_test1,y_pred_regressor))

0.14311194819097206
0.8288279055232558


# Q3) Write a Python code snippet to find the optimal value of K for the KNN classifier algorithm using cross-validation on load_iris dataset in sklearn.datasets.

In [63]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.neighbors import KNeighborsClassifier

# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Range of K values to try
k_values = np.arange(1, 21)

# List to store cross-validation scores for different K values
cv_scores = []

# Perform cross-validation for each K value
for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    scores = cross_val_score(knn, X_train, y_train, cv=5, scoring='accuracy')
    cv_scores.append(np.mean(scores))

# Find the optimal K value with the highest mean cross-validation score
optimal_k = k_values[np.argmax(cv_scores)]
best_cv_score = np.max(cv_scores)

print("Optimal K:", optimal_k)
print("Cross-Validation Score:", best_cv_score)

# Train the KNN classifier with the optimal K value on the full training set
optimal_knn = KNeighborsClassifier(n_neighbors=optimal_k)
optimal_knn.fit(X_train, y_train)

# Evaluate the optimal KNN classifier on the test set
test_accuracy = optimal_knn.score(X_test, y_test)
print("Test Set Accuracy:", test_accuracy)


Optimal K: 3
Cross-Validation Score: 0.9583333333333334
Test Set Accuracy: 1.0


# Q4) Implement the KNN regressor algorithm with feature scaling on load_boston dataset in sklearn.datasets.

In [65]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.datasets import fetch_california_housing
from sklearn.preprocessing import StandardScaler

housing=fetch_california_housing()

X1=pd.DataFrame(data=housing.data,columns=housing.feature_names)
y1=housing.target


# Train test split
X_train1,X_test1,y_train1,y_test1=train_test_split(X1,y1,test_size=1/3,random_state=10)

# standardization
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train1)
X_test_scaled=scaler.transform(X_test1)

knnr=KNeighborsRegressor()
knnr.fit(X_train_scaled,y_train1)

y_pred_regressor=knnr.predict(X_test_scaled)

from sklearn.metrics import r2_score,mean_absolute_error
print('The new r2 square is:',r2_score(y_test1,y_pred_regressor))
print('The new mean absolute error is: ',mean_absolute_error(y_test1,y_pred_regressor))

The new r2 square is: 0.6984679011565758
The new mean absolute error is:  0.4319610563953489


# Q5) Write a Python code snippet to implement the KNN classifier algorithm with weighted voting on load_iris dataset in sklearn.datasets.

In [69]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

data=load_iris()
X=pd.DataFrame(data=data.data,columns=data.feature_names)
y=data.target

# Train test split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=1/3,random_state=10)

knn_d=KNeighborsClassifier(weights='distance')
knn_d.fit(X_train,y_train)

y_pred=knn_d.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.96
[[15  0  0]
 [ 0 17  2]
 [ 0  0 16]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      0.89      0.94        19
           2       0.89      1.00      0.94        16

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



# Q6) Implement a function to standardise the features before applying KNN classifier.

In [70]:
def standard_scaling(X_train,X_test):
    from sklearn.preprocessing import StandardScaler
    scaler=StandardScaler()
    X_train_scaled=scaler.fit_transform(X_train1)
    X_test_scaled=scaler.transform(X_test1)
    
    return X_train_scaled,X_test_scaled

# Q7) Write a Python function to calculate the euclidean distance between two points.

In [71]:
import numpy as np

# Let us assume that the input is 2 points in the form of an array, we convert that ordinary array to a numpy array which makes it easy to perform mathematical operations of numpy.

def euclidean_distance(point1,point2):
    point1=np.array(point1)
    point2=np.array(point2)
    
    if point1.shape!=point2.shape:
        raise ValueError("Points must have the same dimensionality.")
        
    # the dimensions of both points must be the same, we can not determine the distance between 3 dimensional and a 1 dimensional point.
    
    squared_difference=(point1-point2)**2
    

    distance=np.sqrt(np.sum(squared_difference))
    
    return distance

# Q8) Write a Python function to calculate the manhattan distance between two points.

In [72]:
import numpy as np

# Let us assume that the input is 2 points in the form of an array, we convert that ordinary array to a numpy array which makes it easy to perform mathematical operations of numpy.

def manhattan_distance(point1,point2):
    point1=np.array(point1)
    point2=np.array(point2)
    
    if point1.shape!=point2.shape:
        raise ValueError("Points must have the same dimensionality.")
        
    # the dimensions of both points must be the same, we can not determine the distance between 3 dimensional and a 1 dimensional point.
    
    distance=np.sum(np.abs(point1-point2))
    
    return distance